### ISSUE TITLE
loss值不下降

### ISSUE THREAD

**Issue by JiHaoqina** [sfzhang15/FaceBoxes#12]
您好，我按照您的步骤重新训练了一遍，发现loss值下降到4左右就降不下去了，基本都在3+~4+的范围内，请问您训练的时候也会这样吗

**Comment by sfzhang15** [comment]
@JiHaoqina 
是的

**Comment by yujian0534** [comment]
> 好的，谢谢

请问一下 你的训练时间大概多久
