### ISSUE TITLE
batch_size问题

### ISSUE THREAD

**Issue by yyfyan** [sfzhang15/FaceBoxes#14]
由于GPU的原因，我只能设置更小的batch_size，这样的话，迭代次数和学习率该如何调整呢？能否分享点经验。

**Comment by sfzhang15** [comment]
@yyfyan 
FaceBoxes训练应该占的显存不多呀，你的GPU显存是多少?

**Comment by yyfyan** [comment]
6G显存，经常会出现这个问题：）

**Comment by yyfyan** [comment]
@sfzhang15
6G显存，经常会出现这个问题：）

**Comment by yyfyan** [comment]
16张是没问题的。32的时候电脑卡了：）

**Comment by yyfyan** [comment]
@sfzhang15
16张是没问题的。32的时候电脑卡了：）

**Comment by sfzhang15** [comment]
@yyfyan 
那一张卡放16张，solver里的iter_size改成2就行了，其它不用改

**Comment by yyfyan** [comment]
OK，谢谢回复。

**Comment by luckynote** [comment]
> @yyfyan
> 那一张卡放16张，solver里的iter_size改成2就行了，其它不用改
您好，我并未在solver中找到iter_size这个变量，请问是设置默认值了吗？

**Comment by sfzhang15** [comment]
@luckynote 
默认应该是1
