### ISSUE TITLE
faceboxes.caffemodel iter 是多少次后的结果

### ISSUE THREAD

**Issue by luckynote** [sfzhang15/FaceBoxes#15]
首先，非常感谢你们作出的工作，那非常棒。
针对您的model，我有以下两个疑问，希望得到解答：
1. 请问您提供的faceboxes.caffemodel, 是训练iter多少次后的model？
2. 该model使用的数据集是WIDER FACE的完整数据集吗？

**Comment by sfzhang15** [comment]
@luckynote 
1. 就是最后一次迭代，不过最后一次迭代的结果不一定是最好的，你可以把最后几个模型都测一下，选个最好的
2. 只用了WIDER FACE的training subset

**Comment by luckynote** [comment]
好的，非常感谢！
