### ISSUE TITLE
WINDER_FACE 自定义生成 LMDB 文件

### ISSUE THREAD

**Issue by luckynote** [sfzhang15/FaceBoxes#16]
您好，我使用以下两个命令生成自己的LMDB文件，
./data/WIDER_FACE/create_list.sh
./data/WIDER_FACE/create_data.sh
但是，我无法执行成功！
请问，有详细的注释说明，如何配置这两个文件吗？

**Comment by sfzhang15** [comment]
@luckynote 
如果你要是用提供的文件生成LDDB，得先把WIDER FACE转成VOC的格式，你可以参考这个https://github.com/albanie/wider2pascal

**Comment by alexcruz0202** [comment]
Hi, @sfzhang15 . Thanks for sharing your work.
When we use /data/WIDER_FACE/create_data.sh, shall we put 'width' and 'height' to 0 in order to create lmdb for train?

**Comment by sfzhang15** [comment]
@alexcruz0202 
When you transform WIDER FACE to the format of VOC, you can read the image and put its 'width' and 'height' into the xml file, and then run /data/WIDER_FACE/create_data.sh.
