### ISSUE TITLE
opencv的dnn 调用问题

### ISSUE THREAD

**Issue by simmonchan** [sfzhang15/FaceBoxes#17]
你好！ 我在我的电脑上复现了，训练出了模型，然后想使用c++的opencv进行调用caffe，发现出现这个错误：
[libprotobuf ERROR /home/chan/software/opencv-3.3.0/3rdparty/protobuf/src/google/protobuf/text_format.cc:298] Error parsing text-format caffe.NetParameter: 1761:15: Message type "caffe.PriorBoxParameter" has no field named "fixed_size".
OpenCV Error: Unspecified error (FAILED: ReadProtoFromTextFile(param_file, param). Failed to parse NetParameter file: /home/chan/桌面/Face_demo/demo/faceboxes_deploy.prototxt) in ReadNetParamsFromTextFileOrDie, file /home/chan/software/opencv-3.3.0/modules/dnn/src/caffe/caffe_io.cpp, line 1137
是opencv的dnn与这个caffe不符合？

**Comment by simmonchan** [comment]
你好！就是opencv3.3以上有一个dnn的模块，可以用来调用深度学习的一些框架，然后我发现好像不支持faceboxes

**Comment by richipower** [comment]
hello! I was trying this in opencv.. yes it is because of the new layers, some layers in opencv have a different implementation than your or SSD caffe layers, an example is that layer: "PriorBox"

**Comment by sfzhang15** [comment]
@simmonchan @richipower 
Yes. These are some newly added layers that maybe not exit in opencv. If you want to conduct inference via opencv, these new layers should be added.

**Comment by 121786404** [comment]
你增加的层，opencv都是支持的
opencv\modules\dnn\src\layers\permute_layer.cpp
opencv\modules\dnn\src\layers\detection_output_layer.cpp
opencv\modules\dnn\src\layers\prior_box_layer.cpp
目前发现prior_box_layer.cpp的参数，你的实现和opencv不同，打印的错误log是
  prior_box_param {
    min_size: 32
    min_size: 64
    min_size: 128
    clip: false
    variance: 0.1
    variance: 0.1
    variance: 0.2
    variance: 0.2
    step: 32
    offset: 0.5
  }
prior_box_param 里面min_size只能有一个，跑到这里就出问题了。
