### ISSUE TITLE
Hello, I have a question about output output dimension.

### ISSUE THREAD

**Issue by huang229** [sfzhang15/FaceBoxes#21]
Why does inception_a3_concat_mbox_loc output 84 dimensions, while conv3_2_mbox_loc and conv4_2_mbox_loc output 4 dimensions?Thank you!!!

**Comment by sfzhang15** [comment]
@huang229 
Becasue we use the anchor densification strategy, for more detaild please refer to the paper.

**Comment by huang229** [comment]
谢谢，看过论文了，很机智的anchor平铺策略。不过我训练你提到的公共人脸数据集时，损失值下降到四点多就下不去了，不知道你那边是不是一样？

**Comment by huang229** [comment]
谢谢，看过论文了，很机智的anchor平铺策略。不过我训练你提到的公共人脸数据集时，损失值下降到四点多就下不去了，不知道你那边是不是一样，这是否正常？

**Comment by sfzhang15** [comment]
@huang229 
你好，我们这边训练到最后loss也是3左右，你可以测一测精度是否差不多。

**Comment by huang229** [comment]
谢谢
