### ISSUE TITLE
感受野是怎样计算得到的?

### ISSUE THREAD

**Issue by yongtaoge** [sfzhang15/FaceBoxes#23]
请教一下同一层含有不同感受野是怎样计算的.

![rf](https://user-images.githubusercontent.com/22744013/52784523-59b57980-3090-11e9-9ae9-fb6c8bb50f72.png)

**Comment by sfzhang15** [comment]
@yongtaoge 
Inception有多个分支，使得后面的每一层上都有多个不同的分支，我们是计算同一层上不同分支的感受野得到的

**Comment by yongtaoge** [comment]
谢谢!
