### ISSUE TITLE
prototxt

### ISSUE THREAD

**Issue by yyfyan** [sfzhang15/FaceBoxes#24]
你好，以前使用Pytorch，对caffe里prototxt文件生成不是很了解，什么方法能快速生成呢？例如FaceBoxes，里面的层都是新的，不能使用现成的网络改。：）

**Comment by sfzhang15** [comment]
@yyfyan 
你好，可以参考[RefineDet](https://github.com/sfzhang15/RefineDet/blob/master/examples/refinedet/VGG16_VOC2007_320.py), 里头就是用python生成prototxt的，所有的层和网络都在[这个文件](https://github.com/sfzhang15/RefineDet/blob/master/python/caffe/model_libs.py)里定义的

**Comment by yyfyan** [comment]
谢谢。懂了。：）
