### ISSUE TITLE
Could the code be run on Windows 10 with VS2015 or VS 2017?

### ISSUE THREAD

**Issue by ardeal** [sfzhang15/FaceBoxes#25]
Hi,

Could the code be run on Windows 10 with VS 2015 or VS 2017?
What version of Windows and VS you are using to run the code?

Thanks and Best Regards,
Ardeal

**Comment by sfzhang15** [comment]
@ardeal 
I did not run the code on Windows. All the inference codes are based on C++, so I think it can run at Window. If you are familar with C++ on Windows, you can try to run the code on Windows.

**Comment by ardeal** [comment]
Hi Dr. Zhang,
Many thanks for your reply!
I am good at C++, and trying to use cmake gui to configure your faceboxes C++ code. however, some dependencies in your Dependencies.cmake couldn't be satisfied on Winows 10. 

Especially, boost 1.46.0 is required in your Dependencies.cmake file.  As you know, boost 1.46.0 is old and it is not compatible with VS 2015 or VS2017.

I am not sure whether newer version of boost is compatible with your code.

Thanks and Best Regards,
Ardeal

**Comment by Tomhouxin** [comment]
![image](https://user-images.githubusercontent.com/23637856/53398803-7f724500-39e5-11e9-9d99-65cd3501b5ba.png)
I ran into this problem with caffe not supporting prior_box_parm

**Comment by sfzhang15** [comment]
@ardeal 
My senior has run the inference of FaceBoxes on windows, he suggests to use VS2013 to solve this issue. You can try it.

**Comment by sfzhang15** [comment]
@Tomhouxin 
Do you use the right path of caffe.prototxt?

**Comment by Tomhouxin** [comment]
@sfzhang15 
I found your latest update is 640*480，So
I use this  [https://github.com/zeusees/FaceBoxes/blob/master/faceboxes-without-dense/faceboxes_deploy.prototxt](url)

**Comment by sfzhang15** [comment]
@Tomhouxin 
I mean when you build the code, do you use the right path of caffe.prototxt?

**Comment by Tomhouxin** [comment]
@sfzhang15 
Yes

**Comment by sfzhang15** [comment]
The code is built successfully?

**Comment by Tomhouxin** [comment]
@sfzhang15 
Yes, when I run exe, give me this error

**Comment by ardeal** [comment]
Hi Dr. Zhang,

do you use the following LMDB:
http://www.lmdb.tech/doc/index.html

where did you download the source code of LMDB?

Thanks and Best Regards,
Ardeal

**Comment by sfzhang15** [comment]
@Tomhouxin 
According to the error message, the prior_box_param does not exit, it should be in the caffe.prototxt. You can check whether the caffe.prototxt you used has the prior_box_param.

**Comment by sfzhang15** [comment]
@ardeal 
We use LMDB-0.89 and install via `pip install lmdb`.
