### ISSUE TITLE
将faceboxes网络转化为多目标检测

### ISSUE THREAD

**Issue by yujian0534** [sfzhang15/FaceBoxes#26]
你好，我尝试将你的网络改变成多目标的结构，但是检测出来的结果有很多杂乱的框，如果想修改成多目标的形式，有哪些需要修改的地方吗？

**Comment by sfzhang15** [comment]
@yujian0534 
你好，FaceBoxes的网络比较小，做人脸检测还够用，如果做多目标检测，你可以使用[SSD](https://github.com/weiliu89/caffe/tree/ssd)、[RefineDet](https://github.com/sfzhang15/RefineDet)等算法，如果你想加速，可以自己设计小网络或使用其他的轻量级的网络。
