### ISSUE TITLE
Facial landmarks detection

### ISSUE THREAD

**Issue by RunningLeon** [sfzhang15/FaceBoxes#27]
Hi,
Great job. Its cpu real-time speed is really fast. Wonder how to add facial landmarks detection on your net.
Do you have any schedule to release this kind of work?
Thanks a lot.

**Comment by sfzhang15** [comment]
@RunningLeon 
We use CelebA and WIDER FACE to jointly train the model. Comparing to the detection, we plus anthor branch same as regression branch to do facial landmarks detection, i.e., every anchor has five initial landmarks to regress the gt landmarks. The schedule to release landmark model depends on our lab teachers.

**Comment by liny23** [comment]
@sfzhang15 Is the accuracy of the relevant data correct?

**Comment by sfzhang15** [comment]
@liny23 
I don't understand your question very well, please describe your problem more clearly

**Comment by liny23** [comment]
paper about landmark and result in public dataset

**Comment by sfzhang15** [comment]
@liny23 
The paper about joint face and landmark detection will be public soon.

**Comment by onzone** [comment]
On which data you are training your landmarks on?? For jointly learning face detection and landmark detection you should have face detection as well as landmark labels...Wider face has face detection labels and other landmark detection dataset is not good for face detection(either only one face is there in the image or if multiple faces are present in the image only landmark of one face is given)..So are there any dataset that is good for joint training??

**Comment by sfzhang15** [comment]
@onzone 
We use WIDER FACE and CelebA to jointly train face and landmark detection. WIDER FACE only has the face bbox so it just compute the classification and regression loss, while CelebA has the face bbox and landmard so it compute all the losses. We use some data augmentation to enrich the faces in CelebA. The details refer to our forthcoming paper.

**Comment by onzone** [comment]
@sfzhang15 Thank you for your feedback.
