### ISSUE TITLE
main function of Faceboxes source code

### ISSUE THREAD

**Issue by ardeal** [sfzhang15/FaceBoxes#29]
Hi,

I checked all your source code, but I didn't find out the main function of your source code.
Could you please kindly tell me where the main function of faceboxes is?

Thanks and Best Regards,
Ardeal

**Comment by sfzhang15** [comment]
@ardeal 
You can refer to [the official example](https://github.com/BVLC/caffe/blob/master/examples/cpp_classification/classification.cpp).

**Comment by ardeal** [comment]
Hi Dr. Zhang,

I know the official example of Caffe.
What I don't know is the main function of your algorithms/code?

Thanks and Best Regards,
Ardeal

**Comment by sfzhang15** [comment]
@ardeal 
The main function is the same as the official example of Caffe. You may need to write a new main that takes  trained model and prototxt, then initialize the network like [this function](https://github.com/BVLC/caffe/blob/master/examples/cpp_classification/classification.cpp#L48-L84), get the detection like [this function](https://github.com/BVLC/caffe/blob/master/examples/cpp_classification/classification.cpp#L150-L169).  When you successfully initialize the network and process the input, the [net_->Forward()](https://github.com/BVLC/caffe/blob/master/examples/cpp_classification/classification.cpp#L162) will output the detections.

**Comment by ardeal** [comment]
Hi Dr. Zhang,
Thanks for your reply!

Could you please share your python code that calsl caffe model?

Best Regards,
Ardeal

**Comment by sfzhang15** [comment]
@ardeal 
Please refer to [demo.py](https://github.com/sfzhang15/FaceBoxes/blob/master/test/demo.py).

**Comment by ardeal** [comment]
OK,,,
I got it.
Thanks Dr. Zhang!
