### ISSUE TITLE
caffe.LayerParameter has no field named permute_param

### ISSUE THREAD

**Issue by ardeal** [sfzhang15/FaceBoxes#30]
Hi Dr. Zhang,

I have built the latest BVLC caffe on Windows 10 and VS2015, and I am trying to run your code draw_net.py on Python 3.5.

The input_net_proto_file is:
models\faceboxes\deploy.prototxt

The model file is downloaded from your tutorials link:
faceboxes.caffemodel

I am experiencing the following issue:

```C
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.3.3\helpers\pydev\pydevd.py", line 1741, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.3.3\helpers\pydev\pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.3.3\helpers\pydev\pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.3.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/code_cv/face_detection/FaceBoxes/python/draw_net.py", line 66, in <module>
    main()
  File "D:/code_cv/face_detection/FaceBoxes/python/draw_net.py", line 52, in main
    text_format.Merge(open(args.input_net_proto_file).read(), net)
  File "C:\ProgramData\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 525, in Merge
    descriptor_pool=descriptor_pool)
  File "C:\ProgramData\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 579, in MergeLines
    return parser.MergeLines(lines, message)
  File "C:\ProgramData\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 612, in MergeLines
    self._ParseOrMerge(lines, message)
  File "C:\ProgramData\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 627, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "C:\ProgramData\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 727, in _MergeField
    merger(tokenizer, message, field)
  File "C:\ProgramData\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 815, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "C:\ProgramData\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 695, in _MergeField
    (message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 1378:3 : Message type "caffe.LayerParameter" has no field named "permute_param".
```

It seems that the caffe version I am using doesn't match the version you are using.
What is the caffe version you are using?
Do you have any other idea to fix this issue?

Thanks and Best Regards,
Ardeal

**Comment by sfzhang15** [comment]
@ardeal 
Hi, we use the caffe from SSD (https://github.com/weiliu89/caffe/tree/ssd), which has some newly added layers, you should use this caffe from SSD or add these new layers to your caffe.

**Comment by ardeal** [comment]
Got it. Many thanks!

I compared your code with BVLC Caffe, and I also compared your code with SSD.
There is great change between SSD and BVLC Caffe, but small change between your code and SSD.

SSD code removed all MSVC related code. That is the reason your codeis very difficult to be built on MSVC.

I have merged back all MSVC related code to your code from BVLC Caffe.
I am able to compiled the code successfully on MSVC but there are a few linking errors .......

**Comment by sfzhang15** [comment]
@ardeal 
If you just want to perform inference, I think adding about trhee new layers (prior_bbox_layer, permute_layer, detection_output_layer) to your caffe is enough.

**Comment by ardeal** [comment]
Hi Dr. Zhang,
Yes,,,,,,,,,
I just would like to run your model on VS or Python to check the performance of your algorithms.
However, I don't have a GPU on Linux to run your code.

If you could guide me to how to those new layers, you will be greatly appreciated!

By the way, I could build BVLC Caffe on Windows and VS 2015 successfully. If you could help me to add your new layers to BVLC Caffe code and build it on VS 2015, all I would like to do is done.

Thanks and Best Regards,

Ardeal

**Comment by sfzhang15** [comment]
@ardeal 
You can follow [the official intruction](https://github.com/BVLC/caffe/wiki/Development) to add these new layers (i.e., prior_bbox_layer, permute_layer, detection_output_layer).

**Comment by ardeal** [comment]
Hi Dr. Zhang,

Many thanks for your help!

I tried to understand those cmake files  and c++ code in BVLC caffe and your faceboxes code, and modified everything according to my understanding.
I have built your code on Windows 10 and VS 2015 successfully. Here are the steps I did:
1) replace all cmake files in your faceboxes with those cmake file in BVLC Caffe.
2) there are many errors in camke files. we need to fixed all errors one by one:
    - 2.1)  add command in Dependencies.cmake  to make sure boost will call dynamic lib but not static lib: 
add_definitions( -DBOOST_ALL_DYN_LINK )
     - 2.2) add command in <caffe_root> CMakeList.txt file: LINK_LIBRARIES(${Caffe_LINKER_LIBS}) to make sure all libs will be added to link comand of compiler.
    - 2.3) Comment out leveldb package in Dependencies.cmake as this package will conflict with boost during compiling.
    - 2.4) remote all PBULIC key word in Dependencies.cmake file and ProtoBuf.cmake file in command list(APPEND Caffe_LINKER_LIBS ${Boost_LIBRARIES}). as the word PUBLIC will be treated as PUBLIC.lib during compiling.
    - 2.5) merge all code related with MSVC  in cpp and hpp files from BVLC caffe to faceboxes source code.
    - 2.6) there are some other modification that I don't remember. 

After those upper modification, faceboxes code could be compiled on Windows 10 and VS2015.


Thanks and Best Regards,
Ardeal

**Comment by sfzhang15** [comment]
@ardeal 
Great job! Hope it will run successfully as soon as possible.
