### ISSUE TITLE
Set CPU-only mode

### ISSUE THREAD

**Issue by ardeal** [sfzhang15/FaceBoxes#31]
Hi,

I tried to run the demo.py file in python, but I got the following error:

```Python
F0311 15:58:18.148229  6000 common.cpp:76] Cannot use GPU in CPU-only Caffe: check mode.
```
however, I have modified the mode to CPU-only mode. Should I modified some other code to disable GPU mode but enable CPU-only mode?

By the way, the faceboxes model was downloaded from the page you publicized your source code:
https://github.com/sfzhang15/FaceBoxes

```Python
os.chdir(caffe_root)
sys.path.insert(0, 'python')
import caffe

caffe.set_device(0)
# caffe.set_mode_gpu()
caffe.set_mode_cpu()

model_def = 'D:/code_cv/face_detection/FaceBoxes/models/faceboxes/deploy.prototxt'
model_weights = 'D:/code_cv/face_detection/FaceBoxes/models/faceboxes/faceboxes.caffemodel'
net = caffe.Net(model_def, model_weights, caffe.TEST)

image = caffe.io.load_image('examples/images/1.jpg')
```

Thanks and Best Regards,
Ardeal

**Comment by sfzhang15** [comment]
@ardeal 
Try to comment out 'caffe.set_device(0)' ?

**Comment by ardeal** [comment]
Hi Dr. Zhang,

Thank you for your help!

I did the following experiments:
Experiment 1:
Set CPU-only = 0 and re-build caffe. If my understanding is correct, CPU and GPU are both supported by the newly built Caffe.
in demo.py file:
```Pyton
caffe.set_device(0)
caffe.set_mode_gpu()
#caffe.set_mode_cpu()
```
re-run demo.py, and I got the following error:
```Python
I0312 09:00:16.459015  9840 layer_factory.hpp:77] Creating layer input
F0312 09:00:16.459015  9840 layer_factory.hpp:81] Check failed: registry.count(type) == 1 (0 vs. 1) Unknown layer type: Input (known types: MemoryData)
*** Check failure stack trace: ***
```
when the code went to:
```Python
net = caffe.Net(model_def, model_weights, caffe.TEST)
```
----------------------------------------------------------
Experiment 2:
using the CPU and GPU version of Caffe and the following configuration:
```Pyton
#caffe.set_device(0)
#caffe.set_mode_gpu()
caffe.set_mode_cpu()
```
I got the same error.
----------------------------------------------------------
Experiment 3:
using the CPU and GPU version of Caffe and the following configuration:
```Pyton
# caffe.set_device(0)
# caffe.set_mode_gpu()
caffe.set_mode_cpu()
```
I got the same error.

In addition, the faceboxes.caffemodel file was download from the link in your code page:
https://github.com/sfzhang15/FaceBoxes

----------------------------------------------------------
Is the model for CPU or GPU?


Do you have any idea about my issue?

Thanks and Best Regards,
Ardeal

**Comment by sfzhang15** [comment]
@ardeal 
It seems the type of input layer is not registered. Your input type is "data"?

**Comment by ardeal** [comment]
The first a few lines in your deploy.prototxt file are:
name: "deploy"
input: "data"
input_shape {
  dim: 1
  dim: 3
  dim: 640
  dim: 480
}

is the input type "data"?

Did I choose the correct input file?
otherwise, what input file should be chosen?

**Comment by ardeal** [comment]
Hi Dr. Zhang,

Thanks for your help!
I am now able to run faceboxes code on VS2015, and the output of algorithms seems to be correct.

But there is something weird. The following is the figure plotted when I run demo.py:


![image](https://user-images.githubusercontent.com/6227348/54177599-be1bfb00-44cd-11e9-9308-4410c953547d.png)

**Comment by sfzhang15** [comment]
@ardeal 
Yes. There are some faces with low scores, maybe becasue they have small scales. You can low the threshold from 0.5 to 0.25 to show all faces, or you can enlarge the image.

**Comment by ardeal** [comment]
I got it!
Many thanks for your help, Dr. Zhang!

**Comment by ahlemlouma** [comment]
i have the same problem can someone help me plz
F0929 20:55:49.671247 6050 base_data_layer.cpp:84] Cannot use GPU in CPU-only Caffe: check mode.
*** Check failure stack trace: ***
Aborted (core dumped)

**Comment by yezhengli-Mr9** [comment]
> i have the same problem can someone help me plz
> F0929 20:55:49.671247 6050 base_data_layer.cpp:84] Cannot use GPU in CPU-only Caffe: check mode.
> *** Check failure stack trace: ***
> Aborted (core dumped)

Any tutorial to switch to CPU-only caffe?`caffe.set_mode_cpu()` seems not enough. I am studying [another problem](https://github.com/airsplay/lxmert/issues/89) anyway.
