### ISSUE TITLE
能否修改prior_box_param，目前opencv的prior_box和你的不同

### ISSUE THREAD

**Issue by 121786404** [sfzhang15/FaceBoxes#35]
增加的层，opencv都是支持的
opencv\modules\dnn\src\layers\permute_layer.cpp
opencv\modules\dnn\src\layers\detection_output_layer.cpp
opencv\modules\dnn\src\layers\prior_box_layer.cpp
目前发现prior_box_layer.cpp的参数，你的实现和opencv不同，打印的错误log是
prior_box_param {
min_size: 32
min_size: 64
min_size: 128
clip: false
variance: 0.1
variance: 0.1
variance: 0.2
variance: 0.2
step: 32
offset: 0.5
}
prior_box_param 里面min_size只能有一个，跑到这里就出问题了。

**Comment by sfzhang15** [comment]
@121786404 
你好，建议你根据我们提供的prior_box_layer修改opencv中的prior_box_layer.cpp去支持多个min_size的输入以及密集化操作。
