### ISSUE TITLE
测试和训练都报错,维度不匹配

### ISSUE THREAD

**Issue by zacks417** [sfzhang15/FaceBoxes#37]
multibox_loss_layer.cpp:139] Check failed: num_priors_ * loc_classes_ * 4 == bottom[0]->channels() (13568 vs. 87296) Number of priors must match number of location predictions.

我知道了，是我的caffe没有这个cpp，我把它加进去编译再试试

**Comment by sfzhang15** [comment]
@zacks417 
你要是用我们提供的caffe才行，因为我们修改了一些文件。
