### ISSUE TITLE
detecting faces in batches

### ISSUE THREAD

**Issue by mstrfx** [sfzhang15/FaceBoxes#38]
Is it possible to detect faces in batches of images?

**Comment by sfzhang15** [comment]
@mstrfx 
Yes, it is. You can put some images in a batch to detect faces. The first dimension of the output is the batch index.

**Comment by mstrfx** [comment]
Thx mate, did some tests on 1080 ti with cuda 9. If someone is interested in results, it took around 130 ms to process a batch of 20 (503, 896) sized images. Might be good if you have around 10 cameras/streams but not so applicable if you have hundreds I guess :(

**Comment by sfzhang15** [comment]
@mstrfx 
Got it! Thanks.
