### ISSUE TITLE
What is the impact of different height and width?

### ISSUE THREAD

**Issue by chenzhi1992** [sfzhang15/FaceBoxes#4]
In your train.prototxt, the height and width is (1024,1024), but in your deploy.prototxt it is (640,480).
What is the impact of different height and width?

**Comment by sfzhang15** [comment]
@chenzhi1992 
The training size is 1024x1024, but you can test any size images since FaceBoxes is fully convolutional netwrok. Besides, the 640x480 in deploy.prototxt is used to measure the inference speed for the VGA-resolution images.
