### ISSUE TITLE
when will you release the imporved version of FaceBoxes with 5 landmarks?

### ISSUE THREAD

**Issue by wait1988** [sfzhang15/FaceBoxes#40]

**Comment by sfzhang15** [comment]
@wait1988 
It depends on our lab teachers. When we get the permission of our teachers, we will release it immediately.

**Comment by wait1988** [comment]
@sfzhang15 Haha,your boss is your boss.

**Comment by sfzhang15** [comment]
@wait1988 
Before graduation, we dare not make decisions without authorization. Sorry about that.

**Comment by simon5u** [comment]
Hi, for faceboxes with 5 landmarks, may I know the impact on FDDB accuracy and testing speed?

**Comment by sfzhang15** [comment]
@simon5u 
95.2@fppi=1000 on FDDB and 51ms for the VGA image.

**Comment by simon5u** [comment]
I see. Any paper on faceboxes with 5 landmarks?

**Comment by sfzhang15** [comment]
@simon5u 
The paper will be released soon.
