### ISSUE TITLE
The algorithm in NVIDIA GTX1080TI is 25fps for 1280*120 pixels' images.

### ISSUE THREAD

**Issue by ayetao** [sfzhang15/FaceBoxes#43]
We try to transfer faceboxes to some other applications. However, we found that the real time of the algorithm in NVIDIA GTX1080TI is 25fps, which is far less than the paper which had about 100fps. What't wrong with that? Could you give me an explain?

**Comment by sfzhang15** [comment]
@ayetao 
We use the [caffe time](http://tutorial.caffe.berkeleyvision.org/tutorial/interfaces.html) to measure the speed. You can try it.
