### ISSUE TITLE
Error 1 google/protobuf/port_def

### ISSUE THREAD

**Issue by zihaozhang9** [sfzhang15/FaceBoxes#49]
`conda install caffe-gpu 
make all -j && make py`

log:
`compilation terminated.
make: *** [.build_release/src/caffe/layers/base_data_layer.o] Error 1
In file included from ./include/caffe/util/cudnn.hpp:8:0,
                 from ./include/caffe/util/device_alternate.hpp:40,
                 from ./include/caffe/common.hpp:19,
                 from src/caffe/data_reader.cpp:6:
.build_release/src/caffe/proto/caffe.pb.h:10:40: fatal error: google/protobuf/port_def.inc: No such file or directory
 #include <google/protobuf/port_def.inc>
`

**Comment by sfzhang15** [comment]
@zihaozhang9 
This issur is about CAFFE, you can search for solutions online.
