### ISSUE TITLE
用ncnn跑速度非常慢。

### ISSUE THREAD

**Issue by qw87494512** [sfzhang15/FaceBoxes#5]
老哥，你这网络设计对移动设备不友好，前几层耗时占80%。用ncnn跑非常慢，可能是ncnn对7x7优化不好。

**Comment by hylrh2008** [comment]
老哥你用ncnn跑的结果对吗？为什么我用ncnn跑的结果完全不对，但是用caffe跑的结果是对的

**Comment by qw87494512** [comment]
老哥只是测一下时间，看可不可用。。pc上确实比另一个网络快一倍，但是用ncnn跑就比慢一倍。

**Comment by hylrh2008** [comment]
老哥我测试了每层网络的运行时间，发现ncnn的extract 整体时间是所有网络时间和的2倍

**Comment by sfzhang15** [comment]
@qw87494512 @hylrh2008 
你们好，由于我没有研究过ncnn，所以不知道需要针对它做哪些优化，我们公布了所有的训练和测试代码，你们可以相应地改进一下结构，重新训练一个模型。
