### ISSUE TITLE
感受野的计算是否存在问题

### ISSUE THREAD

**Issue by li3cmz** [sfzhang15/FaceBoxes#50]
![image](https://user-images.githubusercontent.com/32973240/61855767-4934e500-aef3-11e9-8339-aedca061972f.png)
您好，
      看了一下您的感受野计算，最高的达到了911x911，但是Inception每个分支最终是以concat的形式结合在一起的，而论文的这个图好像是把Inception的每个分支串行起来然后去计算的。实际上，3个Inception，每个是4个分支，代表一共有4x4x4条分支路段，这样算出来的感受野结果好像是应该如下：
![image](https://user-images.githubusercontent.com/32973240/61855921-9add6f80-aef3-11e9-8364-8cd0bd8c7e3c.png)
但是论文的结果仿佛是把所有分支从模型底部到顶部串行起来，就是:
![image](https://user-images.githubusercontent.com/32973240/61856526-e5abb700-aef4-11e9-8427-9a49f6aabed1.png)
![image](https://user-images.githubusercontent.com/32973240/61856549-eba19800-aef4-11e9-82ef-865e9dcef882.png)
![image](https://user-images.githubusercontent.com/32973240/61856555-ef351f00-aef4-11e9-9b07-b8253c009904.png)
上图红色的部分代表每个分支的RF，还有开头两个conv，两个pooling和结尾的两个conv的RF

请问是否是我理解错了呢？还是论文此处的感受野计算是否有点问题呢？

**Comment by sfzhang15** [comment]
@li3cmz 
你好，由于每个检测层后面是跟了一个3x3的卷积核去预测，所以我们算的都是检测层上3x3区域大小的感受野，或者可以说是最后预测的卷积层1x1区域的感受野。

**Comment by li3cmz** [comment]
原来是这样，我重新测试了一遍，结果和论文一致了。十分感谢！
