### ISSUE TITLE
F0731 17:32:46.966609 19825 detection_output_layer.cpp:164] Check failed: num_priors_ * num_loc_classes_ * 4 == bottom[0]->channels() (4000 vs. 25600) Number of priors must match number of location predictions.

### ISSUE THREAD

**Issue by TomaSaya** [sfzhang15/FaceBoxes#51]
Hello, i had successfully build the ssd caffe (https://github.com/weiliu89/caffe/tree/ssd),
and i already download the pre-trained model "faceboxes.caffemodel".
But when i run the following two codes,
    RCNN_Net.reset( new Net<float> (model_dir + "/deploy.prototxt", TEST) );
    RCNN_Net->CopyTrainedLayersFrom(model_dir + "/faceboxes.caffemodel");
I got the following error messages:

F0731 17:32:46.966609 19825 detection_output_layer.cpp:164] Check failed: num_priors_ * num_loc_classes_ * 4 == bottom[0]->channels() (4000 vs. 25600) Number of priors must match number of location predictions.

do you have any idea, thanks

**Comment by sfzhang15** [comment]
@TomaSaya 
We modify some layers of caffe-ssd to implement our method, you should use our caffe codes.
