### ISSUE TITLE
caffe version is the same as pytorch version

### ISSUE THREAD

**Issue by yja1** [sfzhang15/FaceBoxes#52]
is caffe version the same as pytorch version 
https://github.com/zisianw/FaceBoxes.PyTorch

model  same?
priorbox.cpp  same?

**Comment by yja1** [comment]
I want change pytorch version model to caffe version

**Comment by sfzhang15** [comment]
@yja1 
Maybe some differences. We have released caffe and pytorch version, you can use them.
