### ISSUE TITLE
can we run this on raspberry pi and jetson nano kind of devices 

### ISSUE THREAD

**Issue by tomriddle54** [sfzhang15/FaceBoxes#53]
is there any way to run this on raspberry pi device
what would be the approx fps on it

**Comment by sfzhang15** [comment]
@syedmustafa54 
We do not run this on raspberry pi device. If you can run caffe on raspberry pi device, so does faceboxes.

**Comment by tomriddle54** [comment]
Yes I can run caffe on Jetson nano never tried caffe on pi. So Jetson nano has 128 cuda cores how many fps can I get on Jetson nano.

**Comment by sfzhang15** [comment]
@syedmustafa54 
I am not familiar with Jetson nano, you can run this code to test the FPS.
