### ISSUE TITLE
FDDB without upsampling

### ISSUE THREAD

**Issue by yuanli12139** [sfzhang15/FaceBoxes#54]
It seems that in FDDB evaluation, the input image must be upsampled by 3x in order to achieve the performance mentioned in the paper. This adds up the computational cost. Without upsampling, the performance drops a lot. Does this mean FaceBoxes is not good at detecting small faces?

**Comment by sfzhang15** [comment]
@yuanli12139 
FaceBoxes is able to detect  faces larger than 30 pixels.

**Comment by yuanli12139** [comment]
@sfzhang15 
Got it! Thanks for your answer.
