### ISSUE TITLE
windows 跑出来的结果不正确。

### ISSUE THREAD

**Issue by ghost** [sfzhang15/FaceBoxes#55]

**Comment by sfzhang15** [comment]
@passion765 
请参考 #25 #30 #33

**Comment by ghost** [comment]
> @passion765
> 请参考 #25 #30 #33
刚看了上面几楼对我的帮助不大。
同样的代码 在linux 检测出来结果正常， 在windows  编译中的问题都解决后， 跑起来 检测的score
 都比较高 score 大于1 的好几百个。

**Comment by sfzhang15** [comment]
@passion765 
那你对比着linux和window用同一张图片单步调试一下，看看哪里开始出现差异的？会不会是图片读入的通道顺序错了，或者均值减错了等
