### ISSUE TITLE
Expand image augmentation

### ISSUE THREAD

**Issue by yuanli12139** [sfzhang15/FaceBoxes#57]
Hi @sfzhang15, is there any reason why you didn't use `expand_param{}` in training like what SSD and RefineDet did?

**Comment by sfzhang15** [comment]
@yuanli12139 
Expanding is to increase small objects, but FaceBoxes does not detect small faces (<20). Using expanding does not improve the performance.

**Comment by yuanli12139** [comment]
@sfzhang15 
Understood, thanks!
