### ISSUE TITLE
Issue with prediction using OpenCV dnn module

### ISSUE THREAD

**Issue by ghost** [sfzhang15/FaceBoxes#61]
Hii, when I load the model using cv2.dnn.readNetFromCaffe(), it correctly loads model. Then I attach input using net.setInput(). Input size is [1, 3, 640, 480]. Now, when I perform net.forward, I get the following error:
error: OpenCV(4.4.0) /tmp/pip-req-build-civioau0/opencv/modules/dnn/src/layers/detection_output_layer.cpp:225: error: (-215:Assertion failed) (numPriors * _numLocClasses * 4) == total(inputs[0], 1) in function 'getMemoryShapes

**Comment by rich-pel** [comment]
Hello
@nsaoji could you solve it?
I would be really interested to see your solution.
