### ISSUE TITLE
small(<20 pixels) face

### ISSUE THREAD

**Issue by foralliance** [sfzhang15/FaceBoxes#9]
@sfzhang15 HI
paper的3.4节提到：
`filter out these face boxes whose height or width is less than 20 pixels`

在[FAN](https://arxiv.org/abs/1711.07246)中的3.2.1节中，也提到了相似的内容：
`Besides, we calculate the statistics from the WiderFace train set based on the ground-truth face size. As  Figure  3  shows,  more  than  80%  faces  have  an  object scale from 16 to 406 pixel. Faces with small size lack sufficient resolution and therefore it may not be a good choice to include in the training data.`

有个疑问：这种直接从训练集中剔除<20/16的face，就会导致模型对<20/16的face不敏感，那么在检测的时候，肯定会对<20/16的face检测效果很差，**这不直接影响了模型的检测效果么**。不知道这样的理解对吗？？

另外，在[FDNet](https://arxiv.org/abs/1802.02142)中，作者的做法恰恰相反：
`As WIDER FACE dataset contain many extremely tinny faces (<16 pixels width/height), we keep these small proposals (<16 pixels width/height) valid in the training and testing time [13]. The experiments show that our method can achieve better performance. `
相当于保留了所有的小face。

**Comment by sfzhang15** [comment]
@foralliance 
你好，FaceBoxes是为了实际应用，而实际应用中不需要检测太小的人脸，所以训练时我们就过滤了20以下的人脸，故FaceBoxes只能检测>20或25pixel的人脸。
至于FAN和FDNet的做法，就看要不要检小人脸，要检测非常小的人脸是比较难的，需要设置大量的小尺度anchor、训练时也要制定一些策略等，才能保证非常小的人脸能检的不错。如果不检测非常小的人脸，其实在wider face测试时，大家都会用多尺度测试，这样也能检到比较小的人脸。

**Comment by foralliance** [comment]
@sfzhang15 
了解了！非常感谢！！
